# Generated by Django 4.0.2 on 2022-02-23 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Payment Pending', 'Payment Pending'), ('Dispatched', 'Dispatched'), ('Closed', 'Closed')], max_length=30, null=True)),
                ('attachment', models.ImageField(default='', upload_to='order_attachment/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
